spring.application.name=boot002
###################################
###         Business Layer      ###
###################################
#  WebApplication Type Setting   (none : java  / servlet : web )
spring.main.web-application-type=none   
#spring.main.web-application-type=servlet
server.port=8181
server.servlet.context-path=/boot2

# Banner Setting 
spring.main.banner-mode=off
# DataSource Setting 

# JPA Setting 

# Logging Setting 

# Thymeleaf Setting 
spring.thymeleaf.cache=false






